// Livres dans la série Discworld écrites par Terry Pratchett
const discworldBooks = [
    { id: 1, title: "The Colour of Magic" },
    { id: 2, title: "The Light Fantastic"},
    { id: 3, title: "Equal Rites" },
    { id: 4, title: "Mort" },
    { id: 5, title: "Sourcery" },
    { id: 6, title: "Wyrd Sisters" },
    { id: 7, title: "Pyramids" },
    { id: 8, title: "Guards! Guards!" },
    { id: 9, title: "Eric" },
    { id: 10, title: "Moving Pictures" },
    { id: 11, title: "Reaper Man" },
    { id: 12, title: "Witches Abroad" },
    { id: 13, title: "Small Gods" },
    { id: 14, title: "Lords and Ladies" },
    { id: 15, title: "Men at Arms" },
    { id: 16, title: "Soul Music" },
    { id: 17, title: "Interesting Times" },
    { id: 18, title: "Maskerade" },
    { id: 19, title: "Feet of Clay" },
    { id: 20, title: "Hogfather" },
    { id: 21, title: "Jingo" },
    { id: 22, title: "The Last Continent" },
    { id: 23, title: "Carpe Jugulum" },
    { id: 24, title: "The Fifth Elephant" },
    { id: 25, title: "The Truth" },
    { id: 26, title: "Thief of Time" },
    { id: 27, title: "The Last Hero" },
    { id: 28, title: "The Amazing Maurice and His Educated Rodents" },
    { id: 29, title: "Night Watch" },
    { id: 30, title: "The Wee Free Men" },
    { id: 31, title: "Monstrous Regiment" },
    { id: 32, title: "A Hat Full of Sky" },
    { id: 33, title: "Going Postal" },
    { id: 34, title: "Thud!" },
    { id: 35, title: "Wintersmith" },
    { id: 36, title: "Making Money" },
    { id: 37, title: "Unseen Academicals" },
    { id: 38, title: "I Shall Wear Midnight" },
    { id: 39, title: "Snuff" },
    { id: 40, title: "Raising Steam" },
    { id: 41, title: "The Shepherd's Crown" },
];

module.exports = discworldBooks;